version: '3'

services: 

  client:
    container_name: client
    build: 
      context: ./client/
    image: registry.gitlab.com/mukeshsuthar/graphql-mern-docker/client:1.0
    volumes: 
      - ./prod-config/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment: 
      - NODE_ENV=production
    networks: 
      - graphql
    restart: always
    depends_on: 
      - server
  
  server:
    container_name: server
    build: 
      context: ./server/
      target: production
    image: registry.gitlab.com/mukeshsuthar/graphql-mern-docker/server:1.0
    environment: 
      - NODE_ENV=production
    networks: 
      - graphql
    restart: always
    depends_on: 
      - mongo

  mongo:
    image: registry.gitlab.com/mukeshsuthar/graphql-mern-docker/mongo:1.0
    container_name: mongo
    volumes:
      - ./mongo-volume:/data/db
    networks: 
      - graphql

networks:
  graphql: