version: '3'

services: 

  client:
    container_name: client
    image: 761742206819.dkr.ecr.ap-south-1.amazonaws.com/bookshook-client:1.0
    volumes: 
      - ./prod-config/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment: 
      - NODE_ENV=production
    networks: 
      - graphql
    restart: always
    logging:
      driver: awslogs
      options:
        awslogs-group: bookshook
        awslogs-region: ap-south-1
        awslogs-stream-prefix: client
    depends_on: 
      - server
  
  server:
    container_name: server
    image: 761742206819.dkr.ecr.ap-south-1.amazonaws.com/bookshook-server:1.0
    environment: 
      - NODE_ENV=production
    networks: 
      - graphql
    logging:
      driver: awslogs
      options:
        awslogs-group: bookshook
        awslogs-region: ap-south-1
        awslogs-stream-prefix: server
    restart: always
    depends_on: 
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./mongo-volume:/data/db
    logging:
      driver: awslogs
      options:
        awslogs-group: bookshook
        awslogs-region: ap-south-1
        awslogs-stream-prefix: mongo
    networks: 
      - graphql

networks:
  graphql: