version: '3'

services: 

  client:
    container_name: client
    build: 
      context: ./client/
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
      - REACT_APP_PROD_SERVER_URL=http://localhost:9090
    networks: 
      - graphql
    restart: always
    depends_on: 
      - server
  
  server:
    container_name: server
    build: 
      context: ./server/
      target: production
    ports: 
      - 9090:9090
    environment: 
      - NODE_ENV=production
      - PORT=9090
      - mongourl=mongo:27017
    networks: 
      - graphql
    restart: always
    depends_on: 
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    networks: 
      - graphql

networks:
  graphql: